### ISSUE TITLE
Raw HDMA data missing & provided raw data file is not used in scripts

### ISSUE THREAD

**Issue by ledell** [h2oai/article-information-2019#22]
The file noted as the raw/input HDMA data in the [README](https://github.com/h2oai/article-information-2019#datasets) is: [hmda_lar_2018_orig_mtg_sample.csv](https://github.com/h2oai/article-information-2019/blob/master/data/input/hmda_lar_2018_orig_mtg_sample.csv)

However, this file is not used anywhere in the scripts and I am not sure where it comes from, but the fields match at least a subset of what's listed in the [data dictionary](https://github.com/h2oai/article-information-2019/blob/master/data/HMDA%202018%20Schema.xlsx).   I am using this file because it's the only copy of the source data I can find and I want to build some Disparate Impact Analysis demos and it's a nice dataset to use.

The source data used in [hmda_sample_for_paper.py](https://github.com/h2oai/article-information-2019/blob/master/data/scripts/hmda_sample_for_paper.py) is a [hardcoded path](https://github.com/h2oai/article-information-2019/blob/master/data/scripts/hmda_sample_for_paper.py#L1519) that's not available.  So I think there is some disconnect here.  It also contains many more fields than are present in the `hmda_lar_2018_orig_mtg_sample.csv` file -- more refined information, so instead of just `derived_race` (a summary of race of applicant & co-applicant), it will have 5 race fields for each applicant (primary and co-).

**Comment by nickpschmidt** [comment]
The raw data was too large to upload, though it is a publicly available dataset that is easy to download.  I can provide you with a copy of it though -- if I am able to upload the data to my google drive (we just added new security limitations that may not allow me to do that despite it being public data), then I will give you access to it.

**Comment by nickpschmidt** [comment]
@ledell - Let me know where to send the link and I'll get it to you..

**Comment by nickpschmidt** [comment]
I sent the file to Navdeep.
